services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5431:5432'
    networks:
      - internal
  minio:
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    image: minio/minio
    restart: always
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
      MINIO_DEFAULT_BUCKET: default
    command: server /data --console-address ":9001"
    networks:
      - internal
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - internal
    environment:
      REDIS_PASSWORD: default
      REDIS_DB: 0
networks:
  internal:
    name: internal
    driver: bridge
volumes:
  minio_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
